INTERFACE = "wlp1s0"

PORT_SCAN_WINDOW = 10
PORT_SCAN_THRESHOLD = 15

SSH_LOG_PATH = "/var/log/auth.log"
SSH_PORT = 1111
SSH_ATTEMPT_WINDOW = 60
SSH_ATTEMPT_THRESHOLD = 5

DNS_QUERY_THRESHOLD = 50
DNS_SUSPICIOUS_TLDS = [".xyz", ".top", ".tk", ".ml", ".ga", ".cf"]
DNS_LONG_SUBDOMAIN_LEN = 35

ARP_CHECK_INTERVAL = 30

WEB_HOST = "0.0.0.0"
WEB_PORT = 5000
MAX_ALERTS_FEED = 200

LOG_DIR = "logs"
LOG_FILE = "logs/alerts.json"